### ISSUE TITLE
It is ready?

### ISSUE THREAD

**Issue by thenamelessthing** [Ripolin/potato411#1]
@Ripolin hi, I just found your plugin this morning. And I see "coverage 91%".  So my question is: It is ready for use or not yet?  ;-)

Je parle français également...

Amicalement,

**Comment by babfrag** [comment]
@thenamelessthing salut, les 91% correspondent à la couverture du code par les tests automatisés.
Personnellement, j'utilise ce plugin car il utilise l'api officielle de t411.
L'ancien que j'utilisais (couchpotato.provider.t411) se 'contentait' de parser l'html des résultats de recherche.
Ce que j'ai constaté : 
 - La recherche se fait sur les titres originaux + les titres traduits en fr
 - Le hit rate est plus fort
 - La recherche est plus rapide
 - Sur les recherches d'animes, l'ancien plugin que j'utilisais ne trouvait pratiquement jamais rien, avec potato411 cela fonctionne.

Pour l'instant je n'ai rien à lui reprocher.

Cordialement,

**Comment by thenamelessthing** [comment]
@babfrag Super! Merci pour le retour. Je vais installer le tout de ce pas.
