### ISSUE TITLE
Need clarifications

### ISSUE THREAD

**Issue by thenamelessthing** [Ripolin/potato411#2]
> Additional informations
> 
> It's not the purpose of this plugin to manage additional languages for searching torrents. As lucky we are, CouchPotato does this job. Just verify in your config.ini file in your CP_CONFIG_DIR directory that you have the property languages correctly filled in the core section.
> 
> Example :
> 
> [core]
> ...
> languages = fr
> Now CouchPotato is able to retrieve any movie's french title. Just select it and the plugin does the rest.

If we set this in the config.ini (for me the file is called settings.ini?!)

It will search in french and english or only in french?

**Comment by Ripolin** [comment]
Bonsoir,

concernant le nom du fichier _config.ini_, cela provient du fait que j'utilise une image Docker utilisant ce formalisme (cf. [https://github.com/needo37/couchpotato](https://github.com/needo37/couchpotato)). Néanmoins d'après le fichier source [https://github.com/CouchPotato/CouchPotatoServer/blob/master/couchpotato/runner.py](https://github.com/CouchPotato/CouchPotatoServer/blob/master/couchpotato/runner.py) il semble en effet que le nom du fichier de configuration soit par défaut _settings.conf_. Je vais mettre à jour la doc histoire d'éviter toute confusion.

Concernant la recherche, couchpotato lance toujours par défaut une requête en langue anglaise. Ensuite seulement d'autres requêtes suivent en fonction des langues additionnelles ajoutées au travers la propriété _languages_. Enfin couchpotato aggrège les différents résultats. Il n'est donc pas nécessaire d'ajouter la langue anglaise au paramètre languages, couchpotato s'en charge déjà.

A noter que souvent la requête anglaise permet de récupérer un titre français, mais cela n'étant pas toujours le cas, le fait d'ajouter la propriété _languages  = fr_ nous en assure systématiquement.
