### ISSUE TITLE
Titre alternatif

### ISSUE THREAD

**Issue by thenamelessthing** [Ripolin/potato411#3]
Bonjour, peux-tu m'expliquer pourquoi si par exemple j'ajoute le film The BFG et qu'il ne trouve pas ce titre (mais que le titre soit disponible avec un autre nom qui est dans la liste des titres alternatif) qu'il n'essais pas de le trouver avec les titres alternatifs également?

mERCI

**Comment by Ripolin** [comment]
Bonsoir,

En fait je n'ai aucune idée de pourquoi CouchPotato ne passe pas automatiquement au titre alternatif suivant lorsqu'il ne trouve rien  avec le titre en cours de traitement. Peut être qu'il ne souhaite pas spammer les fournisseurs de torrents afin d'éviter un blocage d'IP de la part de ces derniers.

Essaie de leur relayer la question, peut être qu'il te fourniront une meilleure réponse.
